Add celery, fix for #3
takeflight/wagtail-linkchecker pull request #4
Opened 2017-04-03 00:38 UTC by SableWalnut

2017-06-27 03:25 UTC, mx-moth requested changes

2017-06-27 03:25 UTC, mx-moth commented on wagtaillinkchecker/celery.py
> +os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'settings')
Is this required? Not all deployments will have a settings file called 'settings' on their python path, so making this assuming will cause problems for some people.

2017-06-27 03:25 UTC, mx-moth commented on wagtaillinkchecker/migrations/0003_auto_20170627_0940.py
> +# -*- coding: utf-8 -*-
Not a huge thing by any account, but naming your migrations with `./manage.py makemigrations --name '...'` makes changes like this easier to make sense of, and gives developers some hints when running your migrations. Check out the dependencies a few lines down - you can make a good guess at what the wagtailcore migration is doing, but the wagtaillinkchecker migrations are a complete mystery.

2017-06-27 03:25 UTC, mx-moth commented on wagtaillinkchecker/models.py
> +        if self.scan_finished:
Style nitpick: You can save yourself three lines with `return self.scan_finished is not None`

2017-06-27 03:25 UTC, mx-moth commented on wagtaillinkchecker/models.py
> +        return ScanLink.objects.filter(scan=self)
This method does the same thing as `scan.links.all()`, so you can probably ditch it entirely.

2017-06-27 03:25 UTC, mx-moth commented on wagtaillinkchecker/models.py
> +        return self.all_links().filter(invalid=False)
A lot of the methods below can be better placed on a custom ScanLink QuerySet:

```python
class ScanLinkQuerySet(models.QuerySet):
    def valid(self):
        return self.filter(invalid=False)
    def broken(self):
        return self.valid().filter(broken=True)
    # ... and so on

class ScanLink(models.Model):
    # ... the fields
    objects = ScanLinkQuerySet.as_manager()

# Now you can do:
scan = Scan.objects.first()
scan.links.valid()
```

2017-06-27 03:25 UTC, mx-moth commented on wagtaillinkchecker/models.py
> +    scans = ScanLink.objects.filter(page=instance)
This would be better with an `update()` instead:

```python
ScanLink.objects.filter(page=instance).update(page_deleted=True, page_slug=instance.slug)
```

This is more efficient, as the update is done in the database without loading the ScanLink instances in to memory. See [the Django docs for more information](https://docs.djangoproject.com/en/1.11/ref/models/querysets/#update).

2017-06-27 03:25 UTC, mx-moth commented on wagtaillinkchecker/scanner.py
> +    if 'response' in locals():
This is a bad way of doing things. I can see why you are doing it - depending upon the branch taken in the `try: except:` response may or may not be defined - but there are better ways. Consider:

```python
response = None
try:
    response = requests.get(url, verify=True)
    ...
except ...:
    ...

if response is not None:
    # Do one thing
else:
    # Do another
```
Or
```python
try:
    response = requests.get(url, verify=True)
except ...:
    ...
else:
    # This only executes if there were no exceptions thrown,
    # so response will be set
```
Or observe that every `except:` branch finishes in a `return` statement, so `response` will never be undefined at this point.

2017-06-27 03:25 UTC, mx-moth commented on wagtaillinkchecker/scanner.py
> +        if response.status_code not in range(100, 300):
`30x` responses are redirects and are still valid. This should be `range(100, 400)`

2017-06-27 03:25 UTC, mx-moth commented on wagtaillinkchecker/scanner.py
> +        data['error_message'] = 'There was an error connecting to this site.'
This `'error_message'` would have overridden any error message set in the except blocks, except they all have a return statement. As discussed above, `response` will always be defined here so this else branch will never be executed.

2017-06-27 03:25 UTC, mx-moth commented on wagtaillinkchecker/models.py
> +    def save(self, *args, **kwargs):
This method does nothing now and should be removed.

2017-06-27 03:25 UTC, mx-moth commented on wagtaillinkchecker/models.py
> +        if self.page_deleted and self.page_slug:
```python
return self.page_deleted and self.page_slug
```

2017-06-27 03:25 UTC, mx-moth commented on wagtaillinkchecker/tasks.py
> +    if isinstance(link, ScanLink):
Why would `link` ever not be a `ScanLink`? Either `link` will be a ScanLink, or the line above will raise a `ScanLink.DoesNotExist` exception.

2017-06-28 10:29 UTC, SableWalnut commented
@timheap Thanks for your comprehensive review, I believe I have fixed all the issues you have addressed! :)

2017-06-28 10:29 UTC, SableWalnut commented
@timheap Thanks for your comprehensive review, I believe I have addressed all the issues you have rasied! :)

2017-06-28 10:29 UTC, SableWalnut commented
@timheap Thanks for your comprehensive review, I believe I have addressed all the issues you have raised! :)

2017-06-29 00:47 UTC, mx-moth approved these changes

2017-06-29 00:47 UTC, merged